export const updateTimelineItemActivitySecondsKey = Symbol('Обновление секунд активности')
export const setActivitySecondsToCompleteKey = Symbol()
export const createActivityKey = Symbol()
export const deleteActivityKey = Symbol()
export const activitySelectOptionsKey = Symbol()
export const setTimelineItemActivityKey = Symbol()
export const periodSelectOptionsKey = Symbol()
